import XCTest
@testable import WattAI
@testable import WattAnalysis
@testable import WattModels

final class MarkdownReportBuilderTests: XCTestCase {
    private struct Inputs {
        var stats: EpisodeStats
        var timeline: [TimelineEntry]
        var suspects: [Suspect]
        var patterns: PatternFlags
        var samples: [SamplePoint]
    }

    private func makeInputs() -> Inputs {
        let drain = Fixtures.steadyDrain(startPercent: 96, ratePctPerHour: 48, count: 20, thermalState: 2)
        let withProcesses = drain.enumerated().map { i, sample -> SamplePoint in
            var s = sample
            s.fanRPM = [Double(2000 + 200 * i)]
            s.temperatures = ["pACC MTR Temp Sensor0": Double(70 + i)]
            s.processes = Fixtures.writerReaderProcesses(
                writeBytes: 200 * 1024 * 1024,
                readBytes: 250 * 1024 * 1024
            )
            return s
        }
        let stats = StatsBuilder.build(samples: withProcesses)
        let analysis = ProcessCorrelator().correlate(samples: withProcesses)
        let events = [
            UserEventPoint(timestamp: drain[1].timestamp, kind: .powerUnplugged),
            UserEventPoint(timestamp: drain[3].timestamp, kind: .appActivated, appName: "Claude")
        ]
        let timeline = TimelineBuilder.build(samples: withProcesses, events: events, suspects: analysis.suspects)
        return Inputs(
            stats: stats,
            timeline: timeline,
            suspects: analysis.suspects,
            patterns: analysis.patterns,
            samples: withProcesses
        )
    }

    func testRenderedReportContainsAllRequiredSections() {
        let inputs = makeInputs()
        let verdict = Templater.fallbackVerdict(
            stats: inputs.stats,
            suspects: inputs.suspects,
            patterns: inputs.patterns
        )
        let render = MarkdownReportBuilder.RenderInput(
            stats: inputs.stats,
            timeline: inputs.timeline,
            suspects: inputs.suspects,
            patterns: inputs.patterns,
            verdict: verdict,
            generatedByLLM: false,
            samples: inputs.samples,
            watteVersion: "0.1.0",
            helperInstalled: false
        )
        let now = Date(timeIntervalSinceReferenceDate: 800_000_000)
        let md = MarkdownReportBuilder.render(render, now: now)

        for section in ["## At a glance", "## Timeline", "## Prime suspects", "## Recommended actions", "## Raw data"] {
            XCTAssertTrue(md.contains(section), "Missing section: \(section)")
        }
        XCTAssertTrue(md.contains("# "), "Should have headline")
        XCTAssertTrue(md.contains("```csv"), "Raw data should include CSV blocks")
        XCTAssertTrue(md.contains("Templated"), "Footer should mark templated mode when not LLM")
    }

    func testDeterministicSectionsAreByteIdenticalAcrossLLMVsTemplated() {
        let inputs = makeInputs()
        let verdict = Templater.fallbackVerdict(
            stats: inputs.stats,
            suspects: inputs.suspects,
            patterns: inputs.patterns
        )
        let baseInput = MarkdownReportBuilder.RenderInput(
            stats: inputs.stats,
            timeline: inputs.timeline,
            suspects: inputs.suspects,
            patterns: inputs.patterns,
            verdict: verdict,
            generatedByLLM: false,
            samples: inputs.samples
        )
        var llmInput = baseInput
        llmInput.generatedByLLM = true
        let now = Date(timeIntervalSinceReferenceDate: 800_000_000)
        let templated = MarkdownReportBuilder.render(baseInput, now: now)
        let llm = MarkdownReportBuilder.render(llmInput, now: now)

        // Take everything from "## At a glance" onwards (deterministic body).
        guard let templatedRange = templated.range(of: "## At a glance"),
              let llmRange = llm.range(of: "## At a glance") else {
            XCTFail("Reports missing required '## At a glance' section")
            return
        }
        let templatedBody = String(templated[templatedRange.lowerBound...])
        let llmBody = String(llm[llmRange.lowerBound...])
        // Strip the footer line because it differs in mode label by design.
        let strip = { (s: String) -> String in
            s.split(separator: "\n").filter { !$0.hasPrefix("> Generated by Watt") }.joined(separator: "\n")
        }
        XCTAssertEqual(strip(templatedBody), strip(llmBody),
                       "Deterministic sections must be identical regardless of LLM availability")
    }

    func testTimelineRendersUserActionsBeforeSamplePointsAtSameInstant() {
        let inputs = makeInputs()
        let verdict = Templater.fallbackVerdict(
            stats: inputs.stats,
            suspects: inputs.suspects,
            patterns: inputs.patterns
        )
        let render = MarkdownReportBuilder.RenderInput(
            stats: inputs.stats,
            timeline: inputs.timeline,
            suspects: inputs.suspects,
            patterns: inputs.patterns,
            verdict: verdict,
            generatedByLLM: false,
            samples: inputs.samples
        )
        let md = MarkdownReportBuilder.render(render)
        XCTAssertTrue(md.contains("Unplugged"), "Unplug user action should render")
        XCTAssertTrue(md.contains("Claude"), "App activation user action should render")
    }
}
